export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  MARKET: "/market",
  NOTIFICATIONS: "/notifications",
  FORGOT_PASSWORD: "/forgot-password",
  FORGOT_PASSWORD_SET_PASSWORD: "/forgot-password-set-password",
  AUTHENTICATION_BASIC: "/kyc-basic",
  AUTHENTICATION_ADVANCED: "/kyc-advanced",
  PROFILE: "/profile",
  USER_ACCOUNT: "./authProfile",
  BANK_ACCOUNT: "./authProfile",
  
   Cards_Manager:"/services/Cards_Manager",
  WALLET: "/wallet",
  CHANGE_PASSWORD: "/change-password",
  VERIFY_GOOGLE: "/verify/google",
  MULTI_FACTOR: "/multi-factor",
  GOOGLE_AUTH_FLOW: "/google-auth-flow",
  ADD_FRIEND: "/add-friend",
  DEPOSIT: "/deposit",
  CONNECTED_DEVICES: "/services/connected-devices",
  FAQ: "/services/faq",
  BANK_CARDS: "/services/bank-cards",
  WITHDRAWAL: "/withdrawal",
  MARKET_VIEW: '/services/market-view',
  TRADE: {
    ROOT: "/trade",
    BUY: "/trade/buy",
    SELL: "/trade/sell",
  },
  TICKET: {
    ROOT: "/ticket",
    CREATE: "/ticket/create",
  },
  TRANSACTION: {
    ROOT: "/history",
    CRYPTO_HISTORY: "/history/crypto",
    TOMAN_HISTORY: "/history/toman",
    ORDER_HISTORY: "/history/order",
  },
};