export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  MARKET: "/market",
  NOTIFICATIONS: "/notifications",
  FORGOT_PASSWORD: "/forgot-password",
  FORGOT_PASSWORD_SET_PASSWORD: "/forgot-password-set-password",
  AUTHENTICATION_BASIC: "/kyc-basic",
  AUTHENTICATION_ADVANCED: "/kyc-advanced",
  USER_ACCOUNT: "/user-account",
  WALLET: "/wallet",
  CHANGE_PASSWORD: "/change-password",
  VERIFY_GOOGLE: "/verify/google",
  MULTI_FACTOR: "/multi-factor",
  GOOGLE_AUTH_FLOW: "/google-auth-flow",
  CONNECTED_DEVICES: "/connected-devices",
  FAQ: "/faq",
  BANK_CARDS: "/bank-cards",
  WITHDRAWAL_FIAT: "/withdraw/fiat",
  WITHDRAWAL_CRYPTO: "/withdraw/crypto",
  MARKET_VIEW: '/market-view',
  TRADE: {
    ROOT: "/trade",
    BUY: "/trade/buy",
    SELL: "/trade/sell",
  },
  TICKET: {
    ROOT: "/tickets",
    CREATE: "/tickets/create",
  },
  TRANSACTION: {
    ROOT: "/history",
    CRYPTO_HISTORY: "/history/cryptocurrency",
    TOMAN_HISTORY: "/history/toman",
    ORDER_HISTORY: "/history/order",
  },
  ADD_FRIEND: "/add-friend",
  DEPOSIT: "/wallet/deposit",
  DEPOSIT_GATEWAY: "/deposit/gateway",
  DEPOSIT_IDENTIFIER: "/deposit/identifier",
  DEPOSIT_CARD: "/deposit/card",
  DEPOSIT_RECEIPT: "/wallet/deposit/receipt",
  DEPOSIT_WALLET: "/deposit/wallet",
  DEPOSIT_TXID: "/deposit/txid",
};
